package com.rs2;

import com.rs2.model.combat.AttackBonusType;
import com.rs2.model.combat.AttackStyleDefinition;
import com.rs2.model.combat.AttackXpMode;
import com.rs2.model.combat.CombatType;
import java.math.BigInteger;

public final class ServerSettings {
    public static boolean mod2hsEnabled = false;
    public static double mod2hsAttackBonusRate = 1.2;
    public static double mod2hsStrengthBonusRate = 1.2;
    public static boolean wildyBotsUseNewGeneration = false;
    public static int wildyBotsBaseCombatLevel = 50;
    public static int wildyBotsCombatLevelSpread = 5;
    public static boolean wildyBotsIgnoreCombatForDeepWilderness = true;
    public static boolean relogFrozenBotsEnabled = false;
    public static boolean modernCombatSystemEnabled = true;
    public static boolean sqliteHiscoresEnabled = true;
    public static boolean broadcastCheatUsageEnabled = true;
    public static int defaultMovementSystem = 1;
    public static String serverVersion = "v1.0";
    public static final int cacheVersion = Integer.getInteger("prs.cacheVersion", 443);
    public static boolean skipUndefinedNpcSpawns = true;
    public static int maxLevel = 99;
    public static boolean capXpAtMaxLevel = false;
    public static double barrowsRewardRate = 1.0;
    public static int randomEventsMode = 0;
    public static int holidayDropSets = 50;
    public static int holidayDropRespawnTicks = 500;
    public static boolean holidayItemDropsEnabled = true;
    public static int membershipDaysPerPurchase = 14;
    public static boolean content2007Enabled = false;
    public static int fightCaveStartWaveZeroBased = 0;
    public static int rareDropChanceDivisor = -1;
    public static double commonDropRateMultiplier = 1.0;
    public static double uncommonDropRateMultiplier = 1.0;
    public static double rareDropRateMultiplier = 1.0;
    public static double veryRareDropRateMultiplier = 1.0;
    public static int dropRateCap = 512;
    public static boolean customDropRatesEnabled = false;
    public static String launcherJarPath = "";
    public static boolean cacheVerificationShutdownPending = false;
    public static int progressiveXpMode = 0;
    public static int groundItemLifetimeSeconds = 200;
    public static double shopRestockTimeMultiplier = 1.0;
    public static double shopItemMultiplier = 1.0;
    public static double itemRespawnDelayMultiplier = 1.0;
    public static double npcRespawnDelayMultiplier = 1.0;
    public static boolean showSkillUnlocks = false;
    public static boolean dynamicShopPricesEnabled = true;
    public static boolean skipRequirementsForMissingQuests = false;
    public static boolean recolorMissingQuests = false;
    public static int completeMissingQuestsMode = 0;
    public static boolean clueMerchantEnabled = false;
    public static int clueMerchantClueLevel = 1;
    public static int clueMerchantPriceCoins = 50;
    public static boolean clanWarsBotsEnabled = false;
    public static int clanWarsTeamSize = 20;
    public static int clanWarsEventChanceDivisor = 24;
    public static boolean minigameBotsEnabled = false;
    public static int minigameBotCount = 2;
    public static boolean progressiveBotsPrioritizeExisting = false;
    public static boolean instantGrandExchangePriceFluctuationEnabled = true;
    public static boolean instantGrandExchangeEnabled = false;
    public static boolean grandExchangeServerOffersEnabled = true;
    public static int grandExchangeServerOfferCount = 200;
    public static boolean hotzonesForWildyBotsEnabled = false;
    public static boolean backupCharactersEnabled = false;
    public static boolean wildyBotsEnabled = false;
    public static boolean skillingBotsEnabled = false;
    public static boolean tradeBotsEnabled = false;
    public static boolean otherBotsEnabled = false;
    public static boolean progressiveBotsEnabled = false;
    public static boolean wcStyleMiningEnabled = false;
    public static boolean walkingBotsEnabled = false;
    public static boolean lanConnectionsEnabled = false;
    public static int membershipRequirementMode = 0;
    public static int membershipRequirementValue = 0;
    public static boolean idleLogoutEnabled = true;
    public static int otherBotCount = 20;
    public static int skillingBotCount = 50;
    public static int tradeBotCount = 50;
    public static int progressiveBotCount = 10;
    public static boolean freeToPlayWorld = true;
    public static boolean wildernessSlayerEnabled;
    public static int botLoginIdLimit;
    public static boolean grandExchangeEnabled;
    public static boolean tutorialSkipPromptEnabled;
    public static String serverName;
    public static String serverEmulatorName;
    public static boolean showServerEmulatorInWelcome;
    public static String databaseDriverClass;
    public static String databaseJdbcUrl;
    public static String databaseUsername;
    public static String databasePassword;
    public static boolean sqlitePlayerSaveEnabled;
    public static boolean debugModeEnabled;
    /** Strict diagnostics for legacy 377-era behaviour crossing the 443 compatibility layer. */
    public static boolean revision443AuditMode = Boolean.parseBoolean(System.getProperty("prs.audit443", "false"));
    public static boolean developModeEnabled;
    public static boolean controlPanelHiscoresEnabled;
    public static boolean adminInteractionsAllowed;
    public static int serverPort;
    public static boolean itemSpawningEnabled;
    public static boolean funPkEnabled;
    public static boolean pkWorldEnabled;
    public static int loginRestrictionMode;
    public static boolean rsaEnabled;
    public static int clientBuild;
    public static String rsaModulusString;
    public static String rsaPrivateExponentString;
    public static BigInteger rsaModulus;
    public static BigInteger rsaPrivateExponent;
    public static double xpRate;
    public static double questXpRate;
    public static double botXpRateMultiplier;
    public static int botXpRateMode;
    public static int startX;
    public static int startY;
    public static int startPlane;
    public static int respawnX;
    public static int respawnY;
    public static int respawnPlane;
    public static int maxPlayers;
    public static final String[] bonusTypeNames;
    public static boolean diseasingEnabled;
    public static boolean agilityEnabled;
    public static boolean cookingEnabled;
    public static boolean craftingEnabled;
    public static boolean farmingEnabled;
    public static boolean firemakingEnabled;
    public static boolean fishingEnabled;
    public static boolean fletchingEnabled;
    public static boolean herbloreEnabled;
    public static boolean miningEnabled;
    public static boolean prayerEnabled;
    public static boolean runecraftingEnabled;
    public static boolean slayerEnabled;
    public static boolean smithingEnabled;
    public static boolean thievingEnabled;
    public static boolean woodcuttingEnabled;
    public static boolean duelingDisabled;
    public static final int[] DEFAULT_WEAPON_MOVEMENT_ANIMATIONS;
    public static AttackStyleDefinition MAGIC_ATTACK_STYLE;
    public static AttackStyleDefinition DRAGONFIRE_ATTACK_STYLE;
    public static AttackStyleDefinition SARADOMIN_SWORD_ATTACK_STYLE;
    public static final int[] FUN_WEAPON_IDS;
    public static int placeholderObjectId;
    public static final int[] PACKET_LENGTHS;
    public static final int[][][] APPEARANCE_COLOR_RANGES;
    public static final int[][][] APPEARANCE_BODY_PART_RANGES;

    static {
        botLoginIdLimit = 1990;
        grandExchangeEnabled = false;
        tutorialSkipPromptEnabled = true;
        serverName = "RuneScape";
        serverEmulatorName = "Progressive";
        showServerEmulatorInWelcome = true;
        databaseDriverClass = "org.sqlite.JDBC";
        databaseJdbcUrl = "jdbc:sqlite:data/server.db";
        databaseUsername = "";
        databasePassword = "";
        sqlitePlayerSaveEnabled = false;
        debugModeEnabled = false;
        adminInteractionsAllowed = true;
        serverPort = 43594;
        loginRestrictionMode = 0;
        rsaEnabled = true;
        clientBuild = 443;
        rsaModulusString = "126281243334509621910786157961571648139029640444686961553514423188662257084412132099345405190869140255510782101811050242941632064063371431334829733868500675557132805905863594614007916107891529024023784039950030199813062171961096886168210646453313260607895180672957089197913358703168034604511968295223858703073";
        rsaPrivateExponentString = "30652639256685216982113709825788207861142309232862050206651318249008028834075838037084192223878820867367525545502695992564741792805897626221439361069016103707546910916876758973004891298232729104728327473982300624040057756427674392115989911877923828003372350341670381425233062849579939381994254110724498182865";
        rsaModulus = new BigInteger(rsaModulusString);
        rsaPrivateExponent = new BigInteger(rsaPrivateExponentString);
        xpRate = 40.0;
        questXpRate = 40.0;
        botXpRateMultiplier = 40.0;
        botXpRateMode = 1;
        startX = 3093;
        startY = 3104;
        startPlane = 0;
        respawnX = 3222;
        respawnY = 3218;
        respawnPlane = 0;
        maxPlayers = 3000;
        bonusTypeNames = new String[]{"Stab", "Slash", "Crush", "Magic", "Range", "Stab", "Slash", "Crush", "Magic", "Range", "Strength", "Prayer", "Strength Ranged", "Strength Magic"};
        diseasingEnabled = true;
        agilityEnabled = false;
        cookingEnabled = true;
        craftingEnabled = true;
        farmingEnabled = true;
        firemakingEnabled = true;
        fishingEnabled = true;
        fletchingEnabled = true;
        herbloreEnabled = true;
        miningEnabled = true;
        prayerEnabled = true;
        runecraftingEnabled = true;
        slayerEnabled = true;
        smithingEnabled = true;
        thievingEnabled = true;
        woodcuttingEnabled = true;
        duelingDisabled = false;
        DEFAULT_WEAPON_MOVEMENT_ANIMATIONS = new int[]{808, 819, 824};
        MAGIC_ATTACK_STYLE = new AttackStyleDefinition(CombatType.MAGIC, AttackXpMode.MAGIC, AttackBonusType.MAGIC);
        DRAGONFIRE_ATTACK_STYLE = new AttackStyleDefinition(CombatType.MAGIC, AttackXpMode.DRAGONFIRE, AttackBonusType.MAGIC);
        SARADOMIN_SWORD_ATTACK_STYLE = new AttackStyleDefinition(CombatType.MAGIC, AttackXpMode.SARADOMIN_SWORD, AttackBonusType.SLASH);
        (new int[1])[0] = 6529;
        FUN_WEAPON_IDS = new int[]{4566, 1419, 2460, 2462, 2464, 2466, 2468, 2470, 2472, 2474, 2476, 8936, 8938};
        placeholderObjectId = 3550;
        int[] integerValues = new int[257];
        integerValues[3] = 1;
        integerValues[4] = -1;
        integerValues[11] = 1;
        integerValues[14] = 4;
        integerValues[16] = 6;
        integerValues[17] = 2;
        integerValues[18] = 2;
        integerValues[19] = 2;
        integerValues[21] = 2;
        integerValues[23] = 6;
        integerValues[25] = 12;
        integerValues[35] = 8;
        integerValues[36] = 4;
        integerValues[39] = 2;
        integerValues[40] = 2;
        integerValues[41] = 6;
        integerValues[43] = 6;
        integerValues[45] = -1;
        integerValues[53] = 12;
        integerValues[57] = 8;
        integerValues[58] = 8;
        integerValues[59] = 12;
        integerValues[60] = 8;
        integerValues[61] = 8;
        integerValues[70] = 6;
        integerValues[72] = 2;
        integerValues[73] = 2;
        integerValues[74] = 8;
        integerValues[75] = 6;
        integerValues[77] = -1;
        integerValues[79] = 6;
        integerValues[85] = 1;
        integerValues[86] = 4;
        integerValues[87] = 6;
        integerValues[95] = 3;
        integerValues[98] = -1;
        integerValues[101] = 13;
        integerValues[103] = -1;
        integerValues[117] = 6;
        integerValues[120] = 1;
        integerValues[122] = 6;
        integerValues[126] = -1;
        integerValues[128] = 2;
        integerValues[129] = 6;
        integerValues[131] = 4;
        integerValues[132] = 6;
        integerValues[133] = 8;
        integerValues[135] = 6;
        integerValues[139] = 2;
        integerValues[145] = 6;
        integerValues[152] = 1;
        integerValues[153] = 2;
        integerValues[155] = 2;
        integerValues[156] = 6;
        integerValues[164] = -1;
        integerValues[165] = -1;
        integerValues[181] = 8;
        integerValues[183] = 3;
        integerValues[185] = 2;
        integerValues[188] = 8;
        integerValues[189] = 1;
        integerValues[192] = 12;
        integerValues[200] = 2;
        integerValues[208] = 4;
        integerValues[210] = 4;
        integerValues[214] = 9;
        integerValues[215] = 8;
        integerValues[218] = 10;
        integerValues[222] = 3;
        integerValues[226] = -1;
        integerValues[228] = 6;
        integerValues[230] = 1;
        integerValues[234] = 6;
        integerValues[236] = 6;
        integerValues[237] = 8;
        integerValues[238] = 1;
        integerValues[241] = 4;
        integerValues[246] = -1;
        integerValues[248] = -1;
        integerValues[249] = 4;
        integerValues[252] = 6;
        integerValues[253] = 6;
        PACKET_LENGTHS = integerValues;
        APPEARANCE_COLOR_RANGES = new int[][][]{new int[][]{new int[5], {11, 15, 15, 5, 7}}, new int[][]{new int[5], {11, 15, 15, 5, 7}}};
        int[][][] nArrayArray = new int[2][][];
        int[][] nArrayArray2 = new int[2][];
        int[] maleBodyPartRanges = new int[7];
        maleBodyPartRanges[0] = 18;
        maleBodyPartRanges[1] = 26;
        maleBodyPartRanges[2] = 36;
        maleBodyPartRanges[4] = 33;
        maleBodyPartRanges[5] = 42;
        maleBodyPartRanges[6] = 10;
        nArrayArray2[0] = maleBodyPartRanges;
        nArrayArray2[1] = new int[]{25, 32, 41, 9, 35, 44, 17};
        nArrayArray[0] = nArrayArray2;
        nArrayArray[1] = new int[][]{{56, 61, 70, 45, 67, 79, -1}, {60, 66, 78, 55, 69, 81, -1}};
        APPEARANCE_BODY_PART_RANGES = nArrayArray;
    }
}
